---
# tasks file for filewatcher
- name: Filewatch job.
  wait_for:
    timeout: 10
    path: /home/travis/build/hemanth22/hemanth22.filewatcher/files/hemanth.dat
    msg: Timeout
  retries: 10
  register: file_res
  changed_when: false
  until: file_res is success
