---
# tasks file for filewatcher
- name: Filewatch job.
  wait_for:
    timeout: 60
    path: "{{ file_watcher_path }}"
    msg: Timeout
  retries: "{{ max_run_time }}"
  register: file_res
  changed_when: false
  until: file_res is success
