---
# tasks file for filewatcher
- name: Filewatch job.
  wait_for:
    timeout: 10
    path: "{{ file_watcher_path }}"
    msg: Timeout
  retries: 10
  register: file_res
  changed_when: false
  until: file_res is success
