---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  vars:
    file_watcher_path:./files/hemanth.dat
  roles:
    - role: hemanth22.filewatcher
      tags: molecule-idempotence-notest
